<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-16T05:37:12Z" name="Default suite" finished-at="2024-06-16T05:37:39Z" duration-ms="26804">
    <groups>
    </groups>
    <test started-at="2024-06-16T05:37:12Z" name="Default test" finished-at="2024-06-16T05:37:39Z" duration-ms="26804">
      <class name="com.targetTestNG.TargetTestNG">
        <test-method is-config="true" signature="setProperty()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:06:53Z" name="setProperty" finished-at="2024-06-16T11:07:12Z" duration-ms="19653" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setProperty -->
        <test-method is-config="true" signature="geturl()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:07:12Z" name="geturl" finished-at="2024-06-16T11:07:39Z" duration-ms="26681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- geturl -->
        <test-method is-config="true" signature="signin()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:07:39Z" name="signin" finished-at="2024-06-16T11:07:39Z" duration-ms="6" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.targetTestNG.TargetTestNG.signin(TargetTestNG.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signin -->
        <test-method is-config="true" signature="enterDetails()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:07:39Z" name="enterDetails" finished-at="2024-06-16T11:07:39Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterDetails -->
        <test-method signature="purchaseToys()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:07:39Z" name="purchaseToys" finished-at="2024-06-16T11:07:39Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.targetTestNG.TargetTestNG.signin(TargetTestNG.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseToys -->
        <test-method is-config="true" signature="pageValidation()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:07:39Z" name="pageValidation" finished-at="2024-06-16T11:07:39Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageValidation -->
        <test-method is-config="true" signature="close1()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:07:39Z" name="close1" finished-at="2024-06-16T11:07:39Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close1 -->
        <test-method is-config="true" signature="clearCookies()[pri:0, instance:com.targetTestNG.TargetTestNG@44c73c26]" started-at="2024-06-16T11:07:39Z" name="clearCookies" finished-at="2024-06-16T11:07:39Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearCookies -->
      </class> <!-- com.targetTestNG.TargetTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
